const cardsData = [
  {
    id: "1",
    image: "/assets/html.png",
    "pre-title": "Web Development Languages",
    title: "HTML",
    author: "Sarah smith",
  },
  {
    id: "2",
    image: "/assets/css.webp",
    "pre-title": "Web Development Languages",
    title: "CSS",
    author: "David Lee",
  },
  {
    id: "3",
    image: "/assets/javascript.jpg",
    "pre-title": "Web Development Languages",
    title: "JavaScript",
    author: "John Johnson",
  },
  {
    id: "4",
    image: "/assets/jquery.png",
    "pre-title": "Web Development Languages",
    title: "jQuery",
    author: "John Johnson",
  },
  {
    id: "5",
    image: "/assets/angular.png",
    "pre-title": "Frontend Frameworks and Libraries",
    title: "Angular",
    author: "Jessica Davis",
  },
  {
    id: "6",
    image: "/assets/react.webp",
    "pre-title": "Frontend Frameworks and Libraries",
    title: "React",
    author: "Olivia Martinez",
  },
  {
    id: "7",
    image: "/assets/vuejs.jpeg",
    "pre-title": "Frontend Frameworks and Libraries",
    title: "Vue",
    author: "Ava Jones",
  },
  {
    id: "8",
    image: "/assets/nodejs.webp",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Node.js",
    author: "Ava Jones",
  },
  {
    id: "9",
    image: "/assets/expressjs.webp",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Express.js",
    author: "Ava Jones",
  },
  {
    id: "10",
    image: "/assets/ruby.jpeg",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Ruby on Rails",
    author: "Ava Jones",
  },
  {
    id: "11",
    image: "/assets/django.jpeg",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Django",
    author: "Ava Jones",
  },
  {
    id: "12",
    image: "/assets/flask.webp",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Flask",
    author: "Ethan Thompson",
  },
  {
    id: "13",
    image: "/assets/sql.png",
    "pre-title": "Database and APIs",
    title: "SQL",
    author: "Madison Davis",
  },
  {
    id: "14",
    image: "/assets/nosql.png",
    "pre-title": "Database and APIs",
    title: "NoSQL",
    author: "Isabella Wilson",
  },
  {
    id: "15",
    image: "/assets/restapi.jpeg",
    "pre-title": "Database and APIs",
    title: "REST APIs",
    author: "Jacob Garcia",
  },
  {
    id: "16",
    image: "/assets/graphql.png",
    title: "GraphQL",
    "pre-title": "Database and APIs",
    author: "Mia Brown",
  },
  {
    id: "17",
    image: "/assets/oauth.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "OAuth",
    author: "Evelyn Nguyen",
  },
  {
    id: "18",
    image: "/assets/json.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "JSON",
    author: "Lian Hernandez",
  },
  {
    id: "19",
    image: "/assets/ajax.gif",
    "pre-title": "Web Development Concepts and Technologies",
    title: "AJAX",
    author: "Avery Perez",
  },
  {
    id: "20",
    image: "/assets/wai.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "WebSockets",
    author: "Victoria Kim",
  },
  {
    id: "21",
    image: "/assets/responsive.gif",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Responsive Design",
    author: "Ryan Jones",
  },
  {
    id: "22",
    image: "/assets/accessibility.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Accessibilty",
    author: "Samantha Martin",
  },
  {
    id: "23",
    image: "/assets/ux.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "User Experience(UX)",
    author: "Luke Davis",
  },
  {
    id: "24",
    image: "/assets/ui.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "User Interface (UI)",
    author: "Grace Wilson",
  },
  {
    id: "25",
    image: "/assets/design-systems.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Design Systems",
    author: "Noah Martinez",
  },
  {
    id: "26",
    image: "/assets/performance.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Performance Optimization",
    author: "Chloe Taylor",
  },
  {
    id: "27",
    image: "/assets/cross-browser.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Cross-Compatibility",
    author: "David Lee",
  },
  {
    id: "28",
    image: "/assets/seo.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Search Engine Optimization (SEO)",
    author: "Ava Jones",
  },
  {
    id: "29",
    image: "/assets/web-security.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Web Security",
    author: "Gabriel Hernandez",
  },
  {
    id: "30",
    image: "/assets/testing.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Testing and Debugging",
    author: "Avery Perez",
  },
  {
    id: "31",
    image: "/assets/ci-cd.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title:
      "Continuous Integration/Continuous Integration Continuous Integration/Continuous Integration ",
    author: "Madison Davis",
  },
  {
    id: "32",
    image: "/assets/devops.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "DevOps",
    author: "Isabella Wilson",
  },
  {
    id: "33",
    image: "/assets/cloud.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Cloud Computing",
    author: "Jacob Garcia",
  },
  {
    id: "34",
    image: "/assets/docker.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Docker",
    author: "Mia Brown",
  },
  {
    id: "35",
    image: "/assets/microservices.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "MicroServices",
    author: "Evelyn Nguyen",
  },
  {
    id: "36",
    image: "/assets/pwa.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Progressive Web Apps",
    author: "Lian Hernandez",
  },
  {
    id: "37",
    image: "/assets/wai.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Web Accessibility Initiaive (WAI)",
    author: "Avery Perez",
  },
  {
    id: "38",
    image: "/assets/cms.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Content Mangment Systems (CMS)",
    author: "Victoria Kim",
  },
  {
    id: "39",
    image: "/assets/analytics.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Web Analytics",
    author: "Ryan Jones",
  },
];