const cardsData = [
  {
    image: "./assets/html.png",
    "pre-title": "Web Development Languages",
    title: "HTML",
    author: "Sarah smith",
  },
  {
    image: "./assets/css.webp",
    "pre-title": "Web Development Languages",
    title: "CSS",
    author: "David Lee",
  },
  {
    image: "./assets/javascript.jpg",
    "pre-title": "Web Development Languages",
    title: "JavaScript",
    author: "John Johnson",
  },
  {
    image: "./assets/jquery.png",
    "pre-title": "Web Development Languages",
    title: "jQuery",
    author: "John Johnson",
  },
  {
    image: "./assets/angular.png",
    "pre-title": "Frontend Frameworks and Libraries",
    title: "Angular",
    author: "Jessica Davis",
  },
  {
    image: "./assets/react.webp",
    "pre-title": "Frontend Frameworks and Libraries",
    title: "React",
    author: "Olivia Martinez",
  },
  {
    image: "./assets/vuejs.jpeg",
    "pre-title": "Frontend Frameworks and Libraries",
    title: "Vue",
    author: "Ava Jones",
  },
  {
    image: "./assets/nodejs.webp",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Node.js",
    author: "Ava Jones",
  },
  {
    image: "./assets/expressjs.webp",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Express.js",
    author: "Ava Jones",
  },
  {
    image: "./assets/ruby.jpeg",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Ruby on Rails",
    author: "Ava Jones",
  },
  {
    image: "./assets/django.jpeg",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Django",
    author: "Ava Jones",
  },
  {
    image: "./assets/flask.webp",
    "pre-title": "Backend Frameworks and Libraries",
    title: "Flask",
    author: "Ethan Thompson",
  },
  {
    image: "./assets/sql.png",
    "pre-title": "Database and APIs",
    title: "SQL",
    author: "Madison Davis",
  },
  {
    image: "./assets/nosql.png",
    "pre-title": "Database and APIs",
    title: "NoSQL",
    author: "Isabella Wilson",
  },
  {
    image: "./assets/restapi.jpeg",
    "pre-title": "Database and APIs",
    title: "REST APIs",
    author: "Jacob Garcia",
  },
  {
    image: "./assets/graphql.png",
    title: "GraphQL",
    "pre-title": "Database and APIs",
    author: "Mia Brown",
  },
  {
    image: "./assets/oauth.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "OAuth",
    author: "Evelyn Nguyen",
  },
  {
    image: "./assets/json.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "JSON",
    author: "Lian Hernandez",
  },
  {
    image: "./assets/ajax.gif",
    "pre-title": "Web Development Concepts and Technologies",
    title: "AJAX",
    author: "Avery Perez",
  },
  {
    image: "./assets/wai.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "WebSockets",
    author: "Victoria Kim",
  },
  {
    image: "./assets/responsive.gif",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Responsive Design",
    author: "Ryan Jones",
  },
  {
    image: "./assets/accessibility.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Accessibilty",
    author: "Samantha Martin",
  },
  {
    image: "./assets/ux.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "User Experience(UX)",
    author: "Luke Davis",
  },
  {
    image: "./assets/ui.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "User Interface (UI)",
    author: "Grace Wilson",
  },
  {
    image: "./assets/design-systems.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Design Systems",
    author: "Noah Martinez",
  },
  {
    image: "./assets/performance.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Performance Optimization",
    author: "Chloe Taylor",
  },
  {
    image: "./assets/cross-browser.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Cross-Compatibility",
    author: "David Lee",
  },
  {
    image: "./assets/seo.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Search Engine Optimization (SEO)",
    author: "Ava Jones",
  },
  {
    image: "./assets/web-security.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Web Security",
    author: "Gabriel Hernandez",
  },
  {
    image: "./assets/testing.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Testing and Debugging",
    author: "Avery Perez",
  },
  {
    image: "./assets/ci-cd.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title:
      "Continuous Integration/Continuous Integration Continuous Integration/Continuous Integration ",
    author: "Madison Davis",
  },
  {
    image: "./assets/devops.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "DevOps",
    author: "Isabella Wilson",
  },
  {
    image: "./assets/cloud.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Cloud Computing",
    author: "Jacob Garcia",
  },
  {
    image: "./assets/docker.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Docker",
    author: "Mia Brown",
  },
  {
    image: "./assets/microservices.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "MicroServices",
    author: "Evelyn Nguyen",
  },
  {
    image: "./assets/pwa.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Progressive Web Apps",
    author: "Lian Hernandez",
  },
  {
    image: "./assets/wai.jpeg",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Web Accessibility Initiaive (WAI)",
    author: "Avery Perez",
  },
  {
    image: "./assets/cms.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Content Mangment Systems (CMS)",
    author: "Victoria Kim",
  },
  {
    image: "./assets/analytics.png",
    "pre-title": "Web Development Concepts and Technologies",
    title: "Web Analytics",
    author: "Ryan Jones",
  },
];